[profile.default]
src = "contracts"
out = "artifacts"
auto_detect_solc = true

remappings = [
  "forge-std/=node_modules/forge-std/src",
  "ds-test/=node_modules/ds-test/src",
]

libs = ["node_modules"]
